
import type { Department, Permission, Role } from "./types";

export const departments: Department[] = ["Commissioners Office", "High Command", "Command", "NCOS", "Corrections", "Training", "BCSO"];

export const roles: Role[] = ["Developer", "Administrator", "Commissioners Office", "High Command", "Command", "NCOs", "User"];

export const permissions: Permission[] = [
    // Page Access
    'ACCESS_DASHBOARD',
    'VIEW_ROSTER',
    'VIEW_USERS',
    'VIEW_CALLSIGNS',
    'VIEW_SOPS',
    'VIEW_ARCHIVE',
    'ACCESS_COMMAND_CENTER',
    'VIEW_APPLICATIONS',
    'VIEW_LOGS',
    'ACCESS_ADMIN_PANEL',
    'VIEW_ANNOUNCEMENTS',
    'VIEW_CHANGELOGS',
    
    // Actions
    'MANAGE_PERSONNEL', // Promote, Demote, Fire, Edit Status
    'HIRE_PERSONNEL', // Add new personnel from roster or rehire
    'MANAGE_APPLICATIONS', // Approve, Deny
    'DELETE_APPLICATIONS',
    'EDIT_APPLICATION_FORM',
    'MANAGE_BLACKLIST',
    'MANAGE_USERS', // Create users, assign roles
    'DELETE_USERS',
    'MANAGE_ROLES_PERMISSIONS',
    'MANAGE_RANKS',
    'MANAGE_ACCESS_REQUESTS',
    'MANAGE_APP_SETTINGS',
    'MANAGE_ANNOUNCEMENTS',
    'MANAGE_GALLERY',
    'MANAGE_CHANGELOGS',
    'BYPASS_MAINTENANCE_MODE',
];

export const permissionDescriptions: Record<Permission, string> = {
    ACCESS_DASHBOARD: "Access Dashboard Page",
    VIEW_ROSTER: "View Roster Page",
    VIEW_USERS: "View Users Page",
    VIEW_CALLSIGNS: "View Callsigns Page",
    VIEW_SOPS: "View SOPs Page",
    VIEW_ARCHIVE: "View Fired/Resigned Archive",
    ACCESS_COMMAND_CENTER: "Access Command Center",
    VIEW_APPLICATIONS: "View Application Center",
    VIEW_LOGS: "View DOC Logs",
    ACCESS_ADMIN_PANEL: "Access Admin Panel",
    MANAGE_PERSONNEL: "Manage Personnel (Promote, Demote, Fire, Status)",
    HIRE_PERSONNEL: "Hire & Rehire Personnel",
    MANAGE_APPLICATIONS: "Manage Applications (Approve/Deny)",
    DELETE_APPLICATIONS: "Delete Applications",
    EDIT_APPLICATION_FORM: "Edit Application Form",
    MANAGE_BLACKLIST: "Manage DOC Blacklist",
    MANAGE_USERS: "Manage Users & Roles",
    DELETE_USERS: "Permanently Delete Users",
    MANAGE_ROLES_PERMISSIONS: "Manage Permission Groups",
    MANAGE_RANKS: "Manage Ranks",
    MANAGE_ACCESS_REQUESTS: "Manage Access Requests",
    MANAGE_APP_SETTINGS: "Manage Application Settings (e.g. SOPs)",
    VIEW_ANNOUNCEMENTS: "View Dashboard Announcements",
    MANAGE_ANNOUNCEMENTS: "Create and Delete Announcements",
    MANAGE_GALLERY: "Manage Dashboard Photo Gallery",
    VIEW_CHANGELOGS: "View Changelogs Page",
    MANAGE_CHANGELOGS: "Create and Delete Changelogs",
    BYPASS_MAINTENANCE_MODE: "Bypass Maintenance Mode",
};


// Initial permissions map for database seeding.
// This will no longer be the source of truth for the application.
export const initialPermissionsMap: Record<Role, Permission[]> = {
    User: [
        'ACCESS_DASHBOARD',
        'VIEW_ROSTER',
        'VIEW_USERS',
        'VIEW_CALLSIGNS',
        'VIEW_SOPS',
        'VIEW_ANNOUNCEMENTS',
        'VIEW_CHANGELOGS',
    ],
    NCOs: [
        'ACCESS_DASHBOARD',
        'VIEW_ROSTER',
        'VIEW_USERS',
        'VIEW_CALLSIGNS',
        'VIEW_SOPS',
        'VIEW_LOGS',
        'VIEW_APPLICATIONS',
        'VIEW_ANNOUNCEMENTS',
        'VIEW_CHANGELOGS',
    ],
    Command: [
        'ACCESS_DASHBOARD',
        'VIEW_ROSTER',
        'VIEW_USERS',
        'VIEW_CALLSIGNS',
        'VIEW_SOPS',
        'VIEW_LOGS',
        'VIEW_APPLICATIONS',
        'MANAGE_APPLICATIONS',
        'MANAGE_PERSONNEL',
        'HIRE_PERSONNEL',
        'ACCESS_COMMAND_CENTER',
        'MANAGE_BLACKLIST',
        'VIEW_ARCHIVE',
        'VIEW_ANNOUNCEMENTS',
        'MANAGE_ANNOUNCEMENTS',
        'VIEW_CHANGELOGS',
    ],
    "High Command": [
        'ACCESS_DASHBOARD',
        'VIEW_ROSTER',
        'VIEW_USERS',
        'VIEW_CALLSIGNS',
        'VIEW_SOPS',
        'VIEW_LOGS',
        'VIEW_APPLICATIONS',
        'MANAGE_APPLICATIONS',
        'DELETE_APPLICATIONS',
        'EDIT_APPLICATION_FORM',
        'MANAGE_PERSONNEL',
        'HIRE_PERSONNEL',
        'ACCESS_COMMAND_CENTER',
        'MANAGE_BLACKLIST',
        'VIEW_ARCHIVE',
        'MANAGE_APP_SETTINGS',
        'VIEW_ANNOUNCEMENTS',
        'MANAGE_ANNOUNCEMENTS',
        'MANAGE_GALLERY',
        'VIEW_CHANGELOGS',
    ],
    "Commissioners Office": [
        'ACCESS_DASHBOARD',
        'VIEW_ROSTER',
        'VIEW_USERS',
        'VIEW_CALLSIGNS',
        'VIEW_SOPS',
        'VIEW_LOGS',
        'VIEW_APPLICATIONS',
        'MANAGE_APPLICATIONS',
        'DELETE_APPLICATIONS',
        'EDIT_APPLICATION_FORM',
        'MANAGE_PERSONNEL',
        'HIRE_PERSONNEL',
        'ACCESS_COMMAND_CENTER',
        'MANAGE_BLACKLIST',
        'VIEW_ARCHIVE',
        'ACCESS_ADMIN_PANEL',
        'MANAGE_USERS',
        'MANAGE_ACCESS_REQUESTS',
        'MANAGE_APP_SETTINGS',
        'VIEW_ANNOUNCEMENTS',
        'MANAGE_ANNOUNCEMENTS',
        'MANAGE_GALLERY',
        'VIEW_CHANGELOGS',
    ],
    // Administrator and Developer have all permissions, handled separately.
    Administrator: [...permissions],
    Developer: [...permissions],
};
